<?php

$modversion['name'] = _MI_Q4X_NAME;
$modversion['version'] = '1.2';
$modversion['description'] = _MI_Q4X_DESC;
$modversion['credits'] = 'Templates by WismeriL';
$modversion['author'] = 'Eric Houze';
$modversion['help'] = 'help.html';
$modversion['license'] = 'GPL see LICENSE';
$modversion['official'] = 0;
$modversion['image'] = 'q4x_logo.gif';
$modversion['dirname'] = 'quote4xoops';

// Sql file (must contain sql generated by phpMyAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = 'quote4xoops';

// Templates
$modversion['templates'][1]['file'] = 'q4x_index.html';
$modversion['templates'][1]['description'] = 'The template file of the index file';

// Blocks
$modversion['blocks'][1]['file'] = 'quote4xoops.php';
$modversion['blocks'][1]['name'] = _MI_Q4X_BNAME1;
$modvertion['blocks'][1]['description'] = 'Display the quote of the day';
$modversion['blocks'][1]['show_func'] = 'b_q4x_show';
$modversion['blocks'][1]['template'] = 'q4x_block_day.html';

$modversion['blocks'][2]['file'] = 'quote4xoops.php';
$modversion['blocks'][2]['name'] = _MI_Q4X_BNAME2;
$modvertion['blocks'][2]['description'] = 'Display a random quote of the day';
$modversion['blocks'][2]['show_func'] = 'b_q4x_random';
$modversion['blocks'][2]['template'] = 'q4x_block_random.html';

// Menu
$modversion['hasMain'] = 1;

// Search
//$modversion['hasSearch'] = 0;

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu'] = 'admin/menu.php';
